include(${CMAKE_CURRENT_LIST_DIR}/CUDA_STREAM_TEST_BENCH/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/OPTIMIZED_CUDA_TEST_BENCH/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/SERIAL_CODE_TEST_BENCH/sources.cmake)